### PR TITLE
make LocalNode.Kill more persistent and aggressive

### PR DESCRIPTION
**Pull request by apiarian**
Adds some retry logic to the LocalNode.Kill method to make try killing multiple times. Waits for 5 seconds after the first kill, and if the process is still running, sends a second kill and waits for another 10 seconds. If the process is *still* running after that, sends an Interrupt and moves on.

### CODE REVIEW

**Comment by whyrusleeping** [comment]
@apiarian Did you have an issue with iptb not shutting down nodes?

**Comment by Kubuxu** [comment]
Yes. ipfs might sometimes not like to close (stream hang or something) and then iptb stop hangs.

**Comment by whyrusleeping** [comment]
As i was reviewing this, i noticed that the `process.Kill()` actually sends a `SIGKILL` which ipfs doesnt catch for a clean shutdown (we should probably try sending an interupt first, then kill after a timeout).

**Comment by apiarian** [comment]
interrupting instead of killing now

**Comment by apiarian** [comment]
@whyrusleeping the code on master hangs here: https://github.com/apiarian/ipfs-pinbase/blob/no-seriously-do-some-real-work/pinbase/experiments/main_test.go#L68

The code in this PR does stop things, but it takes 15 seconds per node to do so. The `iptb kill` command seems to work right away (the `ipfs daemon`s disappear from the process list quickly)

**Comment by apiarian** [comment]
@whyrusleeping @Kubuxu I've added a couple of helper functions and test code to show the slow node shutdown. you can run `go test -v` in the `util/example` directory to see things in action. Also shows the `ipfs diag cmds` response from the 0 nodes. Takes 30+ seconds for the whole test run to complete, mostly because of the roughly 15 seconds spent killing the nodes in series.

**Comment by apiarian** [comment]
swapping the interrupt and kills in the kill process to sigquit, we get something like this in the daemon.stderr file: https://gist.github.com/apiarian/b850d4352f0602b242a1cf57a6a0bbb1 for one of the nodes. not sure what to make of it, though it does *still* take 15 seconds to kill each node. maybe there's something wrong with the way that the kill code is detecting that the process is still running while trying to kill it? https://github.com/whyrusleeping/iptb/blob/master/util/localnode.go#L246-L249

**Comment by whyrusleeping** [comment]
@apiarian the 'panic' in your gist is because you were sending SIGKILL (go programs dump a stack trace when you send them sigkill).

I'm curious why its taking so long to shut down, I'll investigate sending a sigint first, then a sigkill after a bit to see what goroutines are blocking

**Comment by Kubuxu** [comment]
Yeah, that was the point of SIGQUIT to see which gourotines are still running at that point.

**Comment by whyrusleeping** [comment]
@apiarian Running your example test i can confirm that one of the nodes is still alive after the test. Something fishy is going on here...

**Comment by whyrusleeping** [comment]
@apiarian Heres an interesting thing i noticed, `kill -0 PID` completes successfully if the process is marked as 'defunct' (zombied). zombie processes don't get reaped until their parent is killed.

For some reason, the setsid operative doesnt seem to take effect during your test (which would set the processes parent to '0', and avoid the whole zombie process thing).

A fix is to just add a `p.Wait()` to the beginning of the `kill -0` wait loop.

**Comment by whyrusleeping** [comment]
ref: https://en.wikipedia.org/wiki/Zombie_process

**Comment by apiarian** [comment]
@whyrusleeping yup, that definitely made things way faster. half a second for the util/example test run now.

**Comment by apiarian** [comment]
though i suspect that now the kill code is just wrong. since the wait blocks until the process finishes, and if the process ignored the first interrupt for some reason, it would never return? not sure i know exactly what is going on here anymore

**Comment by whyrusleeping** [comment]
@apiarian Yeah... So its kinda weird. The `Wait` is only there now for usecases like yours, where the parent process hasnt exited yet (the setsid only takes effect once the parent exits). 

Youre right that in the case that the process is hanging trying to do a clean exit, the wait will block. Perhaps we have two goroutines here? One that tries a wait, and another that does the kill(0) wait looping?

**Comment by Kubuxu** [comment]
Other option would be to register signal handler for SIGCHLD, and call wait syscall so zombie is cleaned up or to detect process in zombie state.

**Comment by apiarian** [comment]
Is there perhaps a better way to start the testbed in go tests? Perhaps a way to force setsid to take effect?

**Comment by whyrusleeping** [comment]
@apiarian hrm... not really. You could do an os.Exec callout to `iptb start`, but i don't think you actually want to do that.

I'm really thinking the best way forward is adding the wait in there. even if its a noop in the common case, it doesnt hurt otherwise

**Comment by Kubuxu** [comment]
Go-ipfs now supports `ipfs shutdown` command and also the polling was reworked a bit. See https://github.com/whyrusleeping/iptb/pull/36/files

Please check if it resolves your problem. If it doesn't please open a new issues referencing this PR we will think about it more.

**Pull request closed without merging**
